apiVersion: v1
kind: Pod
metadata:
  name: pod-busybox44
  namespace: default
  labels:
    app: busybox
spec:
  containers:
  - name: busy
    image: busybox
    command:
      - sleep
      - "3600"
